export const Types = {
    GET_STUDENTS: 'GET_STUDENTS',
    GET_STUDENT: 'GET_STUDENT',
    ADD_STUDENT: 'ADD_STUDENT',
    REMOVE_STUDENT: 'REMOVE_STUDENT',
    UPDATE_STUDENT: 'UPDATE_STUDENT',
    ENROLL: 'ENROLL',
    ADD_STUDENT_FILTER: 'ADD_STUDENT_FILTER',
    APPLY_SEARCH_RESULTS: 'APPLY_SEARCH_RESULTS',
}
