export const Types = {
    GET_STAFFS: 'GET_STAFFS',
    GET_STAFF: 'GET_STAFF',
    ADD_STAFF: 'ADD_STAFF',
    REMOVE_STAFF: 'REMOVE_STAFF',
    UPDATE_STAFF: 'UPDATE_STAFF',
    ADD_STAFF_FILTER: 'ADD_STAFF_FILTER',
    APPLY_SEARCH_RESULTS: 'APPLY_SEARCH_RESULTS',
}
