export const Types = {
    GET_INSTRUCTORS: 'GET_INSTRUCTORS',
    GET_INSTRUCTOR: 'GET_INSTRUCTOR',
    ADD_INSTRUCTOR: 'ADD_INSTRUCTOR',
    REMOVE_INSTRUCTOR: 'REMOVE_INSTRUCTOR',
    UPDATE_INSTRUCTOR: 'UPDATE_INSTRUCTOR',
    ADD_INSTRUCTOR_FILTER: 'ADD_INSTRUCTOR_FILTER',
    APPLY_SEARCH_RESULTS: 'APPLY_SEARCH_RESULTS',
}
