export const Types = {
    GET_FOLLOW_UPS: 'GET_FOLLOW_UPS',
    UPDATE_FOLLOW_UP: 'UPDATE_FOLLOW_UP',
    ADD_FOLLOW_UP_FILTER: 'ADD_FOLLOW_UP_FILTER',
    APPLY_SEARCH_RESULTS: 'APPLY_SEARCH_RESULTS',
}
