export const Types = {
    GET_BATCHES: 'GET_BATCHES',
    GET_ALL_BATCHES: 'GET_ALL_BATCHES',
    GET_BATCH: 'GET_BATCH',
    PRINT_ATTENDANCE: 'PRINT_ATTENDANCE',
    ADD_BATCH: 'ADD_BATCH',
    REMOVE_BATCH: 'REMOVE_BATCH',
    UPDATE_BATCH: 'UPDATE_BATCH',
    ADD_BATCH_FILTER: 'ADD_BATCH_FILTER',
    APPLY_SEARCH_RESULTS: 'APPLY_SEARCH_RESULTS',
}
