export const Types = {
    GET_PROGRAMS: 'GET_PROGRAMS',
    GET_PROGRAM: 'GET_PROGRAM',
    ADD_PROGRAM: 'ADD_PROGRAM',
    REMOVE_PROGRAM: 'REMOVE_PROGRAM',
    UPDATE_PROGRAM: 'UPDATE_PROGRAM',
    ADD_PROGRAM_FILTER: 'ADD_PROGRAM_FILTER',
    APPLY_SEARCH_RESULTS: 'APPLY_SEARCH_RESULTS',
}
