export const Types = {
    GET_REGISTRATIONS: 'GET_REGISTRATIONS',
    UPDATE_REGISTRATION: 'UPDATE_REGISTRATION',
    ADD_REGISTRATION_FILTER: 'ADD_REGISTRATION_FILTER',
    APPLY_SEARCH_RESULTS: 'APPLY_SEARCH_RESULTS',
}
