export const Types = {
    GET_ENQUIRY_PROGRAMS: 'GET_ENQUIRY_PROGRAMS',
    ADD_FEEDBACK: 'ADD_FEEDBACK',
    UPDATE_FEEDBACK: 'UPDATE_FEEDBACK',
    GET_BRANCHES: 'GET_BRANCHES',
    ENQUIRY_DETAIL: 'ENQUIRY_DETAIL',
    SUBMIT_ENQUIRY: 'SUBMIT_ENQUIRY',
    GET_ENQUIRIES: 'GET_ENQUIRIES',
    ADD_ENQUIRY_FILTER: 'ADD_ENQUIRY_FILTER',
    APPLY_SEARCH_RESULTS: 'APPLY_SEARCH_RESULTS',
}
