export const Types = {
    GET_ENQUIRY_PROGRAMS: 'GET_ENQUIRY_PROGRAMS',
    SUBMIT_ENQUIRY: 'SUBMIT_ENQUIRY',
    GET_ENQUIRIES: 'GET_ENQUIRIES',
    ADD_ENQUIRY_FILTER: 'ADD_ENQUIRY_FILTER',
    APPLY_SEARCH_RESULTS: 'APPLY_SEARCH_RESULTS',
}
